### PR TITLE
feat: support RaycastAI

### PR DESCRIPTION
**Pull request by Fatpandac**

### CODE REVIEW

**Review by douo — APPROVED** [review]
Thank you! It looks good to me, but it seems to have broken the behavior of `none`. Perhaps we need to add a new preference to config different providers.

**Review by douo — APPROVED** [review]
Thank you! It looks good to me, but it seems to have broken the behavior of `none`. Perhaps we need to add a new preference to config different providers.

**Comment by Fatpandac** [comment]
I'm not sure how to add a new preference to configure RaycastAI.
if we add a checkbox to the config allowing users to choose whether or not to use RaycastAI, we can not disable the text input field for the OpenAI API key when users choose to use RaycastAI.

**Comment by douo** [comment]
> I'm not sure how to add a new preference to configure RaycastAI. if we add a checkbox to the config allowing users to choose whether or not to use RaycastAI, we can not disable the text input field for the OpenAI API key when users choose to use RaycastAI.

Yes, as far as I know, raycast only supports static preferences.

**Pull request merged**
